global:
  scrape_interval: 30s
  external_labels:
    monitor: 'lamassuiot-monitor'

scrape_configs:
  - job_name: 'lamassu'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    consul_sd_configs:
      - server: 'consul-server:8501'
        scheme: 'https'
        datacenter: 'lamassu-dc'
        tls_config:
          ca_file: '/etc/prometheus/certs/consul-server.crt'
        services:
          - enroller
          - ca
          - manufacturing
          - manufacturingenroll
          - scep
          - scepca1
          - scepca2
          - scepca3
          - scepca4
